### ISSUE TITLE
Schedule with IT for attestation: PAUSED check is finished before DACO to EGO runs

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/dac-api#241]
Schedule with IT - to ensure that jobs are scheduled so that the PAUSED check is finished before DACO to EGO runs.

**Comment by anncatton** [comment]
Expiry jobs will be run as part of the batch endpoint created in the api that will run ALL jobs related to expiry and attestation. We can set this schedule in the cron job config and won't need IT's help.

There isn't a way to guarantee the batch jobs run before Daco2Ego, however a possible solution would be to run Daco2Ego more than once a day, so that DACO access is more up-to-date.
